/* 
 * JcDecaux
 *
 * JcDecaux API
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using RestSharp;
using IO.Swagger.Client;
using IO.Swagger.Model;

namespace IO.Swagger.Api
{
    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
        public interface IParksApi : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// Get a park
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="contractName"></param>
        /// <param name="parkNumber"></param>
        /// <returns>Park</returns>
        Park GetPark (string contractName, int? parkNumber);

        /// <summary>
        /// Get a park
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="contractName"></param>
        /// <param name="parkNumber"></param>
        /// <returns>ApiResponse of Park</returns>
        ApiResponse<Park> GetParkWithHttpInfo (string contractName, int? parkNumber);
        /// <summary>
        /// Get all parks of a contract
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="contractName"></param>
        /// <returns>List&lt;Park&gt;</returns>
        List<Park> GetParks (string contractName);

        /// <summary>
        /// Get all parks of a contract
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="contractName"></param>
        /// <returns>ApiResponse of List&lt;Park&gt;</returns>
        ApiResponse<List<Park>> GetParksWithHttpInfo (string contractName);
        #endregion Synchronous Operations
        #region Asynchronous Operations
        /// <summary>
        /// Get a park
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="contractName"></param>
        /// <param name="parkNumber"></param>
        /// <returns>Task of Park</returns>
        System.Threading.Tasks.Task<Park> GetParkAsync (string contractName, int? parkNumber);

        /// <summary>
        /// Get a park
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="contractName"></param>
        /// <param name="parkNumber"></param>
        /// <returns>Task of ApiResponse (Park)</returns>
        System.Threading.Tasks.Task<ApiResponse<Park>> GetParkAsyncWithHttpInfo (string contractName, int? parkNumber);
        /// <summary>
        /// Get all parks of a contract
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="contractName"></param>
        /// <returns>Task of List&lt;Park&gt;</returns>
        System.Threading.Tasks.Task<List<Park>> GetParksAsync (string contractName);

        /// <summary>
        /// Get all parks of a contract
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="contractName"></param>
        /// <returns>Task of ApiResponse (List&lt;Park&gt;)</returns>
        System.Threading.Tasks.Task<ApiResponse<List<Park>>> GetParksAsyncWithHttpInfo (string contractName);
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
        public partial class ParksApi : IParksApi
    {
        private IO.Swagger.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="ParksApi"/> class.
        /// </summary>
        /// <returns></returns>
        public ParksApi(String basePath)
        {
            this.Configuration = new IO.Swagger.Client.Configuration { BasePath = basePath };

            ExceptionFactory = IO.Swagger.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ParksApi"/> class
        /// </summary>
        /// <returns></returns>
        public ParksApi()
        {
            this.Configuration = IO.Swagger.Client.Configuration.Default;

            ExceptionFactory = IO.Swagger.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ParksApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public ParksApi(IO.Swagger.Client.Configuration configuration = null)
        {
            if (configuration == null) // use the default one in Configuration
                this.Configuration = IO.Swagger.Client.Configuration.Default;
            else
                this.Configuration = configuration;

            ExceptionFactory = IO.Swagger.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public String GetBasePath()
        {
            return this.Configuration.ApiClient.RestClient.BaseUrl.ToString();
        }

        /// <summary>
        /// Sets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        [Obsolete("SetBasePath is deprecated, please do 'Configuration.ApiClient = new ApiClient(\"http://new-path\")' instead.")]
        public void SetBasePath(String basePath)
        {
            // do nothing
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public IO.Swagger.Client.Configuration Configuration {get; set;}

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public IO.Swagger.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Gets the default header.
        /// </summary>
        /// <returns>Dictionary of HTTP header</returns>
        [Obsolete("DefaultHeader is deprecated, please use Configuration.DefaultHeader instead.")]
        public IDictionary<String, String> DefaultHeader()
        {
            return new ReadOnlyDictionary<string, string>(this.Configuration.DefaultHeader);
        }

        /// <summary>
        /// Add default header.
        /// </summary>
        /// <param name="key">Header field name.</param>
        /// <param name="value">Header field value.</param>
        /// <returns></returns>
        [Obsolete("AddDefaultHeader is deprecated, please use Configuration.AddDefaultHeader instead.")]
        public void AddDefaultHeader(string key, string value)
        {
            this.Configuration.AddDefaultHeader(key, value);
        }

        /// <summary>
        /// Get a park 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="contractName"></param>
        /// <param name="parkNumber"></param>
        /// <returns>Park</returns>
        public Park GetPark (string contractName, int? parkNumber)
        {
             ApiResponse<Park> localVarResponse = GetParkWithHttpInfo(contractName, parkNumber);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Get a park 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="contractName"></param>
        /// <param name="parkNumber"></param>
        /// <returns>ApiResponse of Park</returns>
        public ApiResponse< Park > GetParkWithHttpInfo (string contractName, int? parkNumber)
        {
            // verify the required parameter 'contractName' is set
            if (contractName == null)
                throw new ApiException(400, "Missing required parameter 'contractName' when calling ParksApi->GetPark");
            // verify the required parameter 'parkNumber' is set
            if (parkNumber == null)
                throw new ApiException(400, "Missing required parameter 'parkNumber' when calling ParksApi->GetPark");

            var localVarPath = "/contracts/{contract_name}/parks/{park_number}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (contractName != null) localVarPathParams.Add("contract_name", this.Configuration.ApiClient.ParameterToString(contractName)); // path parameter
            if (parkNumber != null) localVarPathParams.Add("park_number", this.Configuration.ApiClient.ParameterToString(parkNumber)); // path parameter
            // authentication (ApiKey) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("apiKey")))
            {
                localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "apiKey", this.Configuration.GetApiKeyWithPrefix("apiKey")));
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("GetPark", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<Park>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (Park) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(Park)));
        }

        /// <summary>
        /// Get a park 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="contractName"></param>
        /// <param name="parkNumber"></param>
        /// <returns>Task of Park</returns>
        public async System.Threading.Tasks.Task<Park> GetParkAsync (string contractName, int? parkNumber)
        {
             ApiResponse<Park> localVarResponse = await GetParkAsyncWithHttpInfo(contractName, parkNumber);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Get a park 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="contractName"></param>
        /// <param name="parkNumber"></param>
        /// <returns>Task of ApiResponse (Park)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<Park>> GetParkAsyncWithHttpInfo (string contractName, int? parkNumber)
        {
            // verify the required parameter 'contractName' is set
            if (contractName == null)
                throw new ApiException(400, "Missing required parameter 'contractName' when calling ParksApi->GetPark");
            // verify the required parameter 'parkNumber' is set
            if (parkNumber == null)
                throw new ApiException(400, "Missing required parameter 'parkNumber' when calling ParksApi->GetPark");

            var localVarPath = "/contracts/{contract_name}/parks/{park_number}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (contractName != null) localVarPathParams.Add("contract_name", this.Configuration.ApiClient.ParameterToString(contractName)); // path parameter
            if (parkNumber != null) localVarPathParams.Add("park_number", this.Configuration.ApiClient.ParameterToString(parkNumber)); // path parameter
            // authentication (ApiKey) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("apiKey")))
            {
                localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "apiKey", this.Configuration.GetApiKeyWithPrefix("apiKey")));
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("GetPark", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<Park>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (Park) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(Park)));
        }

        /// <summary>
        /// Get all parks of a contract 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="contractName"></param>
        /// <returns>List&lt;Park&gt;</returns>
        public List<Park> GetParks (string contractName)
        {
             ApiResponse<List<Park>> localVarResponse = GetParksWithHttpInfo(contractName);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Get all parks of a contract 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="contractName"></param>
        /// <returns>ApiResponse of List&lt;Park&gt;</returns>
        public ApiResponse< List<Park> > GetParksWithHttpInfo (string contractName)
        {
            // verify the required parameter 'contractName' is set
            if (contractName == null)
                throw new ApiException(400, "Missing required parameter 'contractName' when calling ParksApi->GetParks");

            var localVarPath = "/contracts/{contract_name}/parks";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (contractName != null) localVarPathParams.Add("contract_name", this.Configuration.ApiClient.ParameterToString(contractName)); // path parameter
            // authentication (ApiKey) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("apiKey")))
            {
                localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "apiKey", this.Configuration.GetApiKeyWithPrefix("apiKey")));
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("GetParks", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<List<Park>>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (List<Park>) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(List<Park>)));
        }

        /// <summary>
        /// Get all parks of a contract 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="contractName"></param>
        /// <returns>Task of List&lt;Park&gt;</returns>
        public async System.Threading.Tasks.Task<List<Park>> GetParksAsync (string contractName)
        {
             ApiResponse<List<Park>> localVarResponse = await GetParksAsyncWithHttpInfo(contractName);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Get all parks of a contract 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="contractName"></param>
        /// <returns>Task of ApiResponse (List&lt;Park&gt;)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<List<Park>>> GetParksAsyncWithHttpInfo (string contractName)
        {
            // verify the required parameter 'contractName' is set
            if (contractName == null)
                throw new ApiException(400, "Missing required parameter 'contractName' when calling ParksApi->GetParks");

            var localVarPath = "/contracts/{contract_name}/parks";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (contractName != null) localVarPathParams.Add("contract_name", this.Configuration.ApiClient.ParameterToString(contractName)); // path parameter
            // authentication (ApiKey) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("apiKey")))
            {
                localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "apiKey", this.Configuration.GetApiKeyWithPrefix("apiKey")));
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("GetParks", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<List<Park>>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (List<Park>) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(List<Park>)));
        }

    }
}
