package org.tempuri;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.4.5
 * 2023-12-04T11:01:48.241+01:00
 * Generated source version: 3.4.5
 *
 */
@WebService(targetNamespace = "http://tempuri.org/", name = "IService1")
@XmlSeeAlso({com.microsoft.schemas._2003._10.serialization.ObjectFactory.class, ObjectFactory.class, org.datacontract.schemas._2004._07.routingserver.ObjectFactory.class, org.datacontract.schemas._2004._07.osmroutingclient.ObjectFactory.class})
public interface IService1 {

    @WebMethod(operationName = "GetDataUsingDataContract", action = "http://tempuri.org/IService1/GetDataUsingDataContract")
    @Action(input = "http://tempuri.org/IService1/GetDataUsingDataContract", output = "http://tempuri.org/IService1/GetDataUsingDataContractResponse")
    @RequestWrapper(localName = "GetDataUsingDataContract", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetDataUsingDataContract")
    @ResponseWrapper(localName = "GetDataUsingDataContractResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetDataUsingDataContractResponse")
    @WebResult(name = "GetDataUsingDataContractResult", targetNamespace = "http://tempuri.org/")
    public org.datacontract.schemas._2004._07.routingserver.CompositeType getDataUsingDataContract(

        @WebParam(name = "composite", targetNamespace = "http://tempuri.org/")
        org.datacontract.schemas._2004._07.routingserver.CompositeType composite
    );

    @WebMethod(operationName = "GetBestTrajet", action = "http://tempuri.org/IService1/GetBestTrajet")
    @Action(input = "http://tempuri.org/IService1/GetBestTrajet", output = "http://tempuri.org/IService1/GetBestTrajetResponse")
    @RequestWrapper(localName = "GetBestTrajet", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetBestTrajet")
    @ResponseWrapper(localName = "GetBestTrajetResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetBestTrajetResponse")
    @WebResult(name = "GetBestTrajetResult", targetNamespace = "http://tempuri.org/")
    public org.datacontract.schemas._2004._07.osmroutingclient.ArrayOfArrayOfPosition getBestTrajet(

        @WebParam(name = "start", targetNamespace = "http://tempuri.org/")
        java.lang.String start,
        @WebParam(name = "end", targetNamespace = "http://tempuri.org/")
        java.lang.String end
    );
}
