
package com.example.serverside;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 3.0.0
 * Generated source version: 3.0
 * 
 */
@WebService(name = "IService1", targetNamespace = "http://tempuri.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface IService1 {


    /**
     * 
     * @param start
     * @param end
     * @return
     *     returns com.example.serverside.ArrayOfArrayOfPosition
     */
    @WebMethod(operationName = "GetBestTrajet", action = "http://tempuri.org/IService1/GetBestTrajet")
    @WebResult(name = "GetBestTrajetResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetBestTrajet", targetNamespace = "http://tempuri.org/", className = "com.example.serverside.GetBestTrajet")
    @ResponseWrapper(localName = "GetBestTrajetResponse", targetNamespace = "http://tempuri.org/", className = "com.example.serverside.GetBestTrajetResponse")
    public ArrayOfArrayOfPosition getBestTrajet(
        @WebParam(name = "start", targetNamespace = "http://tempuri.org/")
        String start,
        @WebParam(name = "end", targetNamespace = "http://tempuri.org/")
        String end);

}
